name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.1.0'

      - name: Run JavaScript file
        run: node index.js

      - name: Commit README
        uses: EndBug/add-and-commit@v9
        with:
          fetch: false
          message: "${{ github.event.time }}"
          add: 'README.md'