name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.1.0'

      - name: Run JavaScript file
        run: node index.js

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Commit changes
        if: env.changes_detected == 'true'
        run: |
          git config --local user.email "safinildan@gmail.com"
          git config --local user.name "lld4n"
          git add .
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}